### ISSUE TITLE
Integrate the Rewritten Nimble

### ISSUE THREAD

**Issue by jeffh** [Quick/Quick#90]
See the [new nimble](https://github.com/quick-bdd/Quick). This is mostly a note to myself which issues are related to this one.

The new Nimble addresses the following open issues:
- [x] #84 Custom Matchers (v0.1.0 beta)
- [x] #82 Test for expectations (v0.1.0 beta)
- [x] #70 Support for `@lazy` property (v0.1.0 beta) -- Needs a test to ensure no regressions.
- [x] #75 Closure and aynchronous expectation tests -- probably still better to add more tests. (v0.1.0 beta)
- [x] #88 Dictionary support to beEmpty() matcher
- [x] #87 Nimble is terrible
- [x] #86 The generic matcher should support Any? expected parameter
- [x] #66 Prettier Objective-C Syntax (at least the Nimble part of it)
- [x] #61 Overload contain() matcher to accept variadic parameters 
- [x] Would close PR #31 WIP for using Generics to allow for more flexible type matching
- [x] Would close PR #23 Test subject is Any, but introduces Swift compiler fatal crash
- [x] #17 Use of C primitive types in expectations

A nice bonus would be to switch the new Nimble test suite to Quick.
